whill_joy2:
  ros__parameters:
    # main process rate
    frequency: 10
    # the duration between the time when LB and RB is pressed
    pressed_duration: 2.0
    # Sequentially, front(0 ~ 2): speed, acceleration, deceleration / back(3 ~ 5): speed, acceleration, deceleration / turn(6 ~ 8): speed, acceleration, deceleration
    # speed rad/s acceleration rad/ss deceleration rad/ss (Motor)
    # whill speed = motor speed * the radius(default: 0.1325m) of tire

    # fm, fa, fd, rm, ra, rd, tm, ta, td  :config
    # 8   10  40  8   10  40  8   10  40  :min
    # ~   ~   ~   ~   ~   ~   ~   ~   ~
    # 60  90  160 30  50  90  35  60  160 :max
    speed_profile_initial: [
      34, 16, 90, 19, 24, 64, 21, 35, 72
    ]
