whill_joy2:
  ros__parameters:
    # if true, permissible to use joystick to control
    use_joycon: true
    # main process rate
    frequency: 10
    # the duration between the time when LB and RB is pressed
    pressed_duration: 2.0
    # Sequentially, front(0 ~ 2): speed, acceleration, deceleration / back(3 ~ 5): speed, acceleration, deceleration / turn(6 ~ 8): speed, acceleration, deceleration
    # speed rad/s acceleration rad/ss deceleration rad/ss (Motor)
    # whill speed = motor speed * the radius(default: 0.1325m) of tire
    # Speed limit: 8 ~ 60
    # Acceleration limit: 10 ~ 90
    # Deceleration limit: 10 ~ 160
    speed_config_vector: [
      "10, 16, 48, 10, 16, 40, 8, 56, 72",
      "15, 16, 64, 10, 16, 56, 10, 56, 72",
      "30, 16, 82, 20, 16, 64, 15, 56, 72",
      "45, 16, 90, 20, 24, 64, 18, 56, 72",
      "57, 16, 90, 20, 24, 64, 14, 28, 64",
      "15, 16, 64, 10, 16, 56, 10, 56, 72"
    ]
    # default speed step
    speed_step: 3