whill_joy2:
  ros__parameters:
    # main process rate
    frequency: 10
    # the duration between the time when LB and RB is pressed
    pressed_duration: 2.0
    # Sequentially, front(0 ~ 2): speed, acceleration, deceleration / back(3 ~ 5): speed, acceleration, deceleration / turn(6 ~ 8): speed, acceleration, deceleration
    # speed rad/s acceleration rad/ss deceleration rad/ss (Motor)
    # whill speed = motor speed * the radius(default: 0.1325m) of tire
    # Speed limit: 8 ~ 60
    # Acceleration limit: 10 ~ 90
    # Deceleration limit: 10 ~ 160
    speed_profile_initial: [
      45, 16, 90, 20, 24, 64, 18, 56, 72
    ]